images:
- name: customers
  newName: ellinj/spring-petclinic-customers-service
  newTag: 0.21.0
- digest: sha256:300d7105f523739b19ab0443031925ded753567a51a398e460a2348b3f1b078f
  name: spring-petclinic-api-gateway
  newName: reg.ellin.net/dev/spring-petclinic-api-gateway
resources:
- helloworld-service-deployment.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization